server:
  port: 7000 # 端口

spring:
  datasource:
    username: root
    password: wenbin123456
    url: jdbc:mysql://47.106.155.227:3306/db_test?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-service # 应用名称

# 自定义配置
name: order-service-default


